from app.models.user import User
from app.models.etudiant import Etudiant
from app.models.entreprise import Entreprise
from app.models.annonce import Annonce
from app.models.annonce_validation_dept import AnnonceValidationDept
from app.models.candidature import Candidature
from app.models.cv import CV
from app.models.embedding import Embedding
from app.models.chef_departement import ChefDepartement
from app.models.notification import Notification
